# Generated by Django 5.0.2 on 2024-12-12 19:09

import ftpapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ftpapp', '0002_person_mobile_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=ftpapp.models.image_upload_to)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
